package codeanalysis.binding;

public enum BoundNodeKind {
    LITERAL_EXPRESSION, UNARY_EXPRESSION, VARIABLE_EXPRESSION, ASSIGNMENT_EXPRESSION, BLOCK_STATEMENT, EXPRESSION_STATEMENT, VARIABLE_DECLARATION_STATEMENT, IF_STATEMENT, ELSE_CLAUSE, WHILE_STATEMENT, BINARY_EXPRESSION
}
