package codeanalysis.binding;

public enum BoundNodeKind {
    LITERAL_EXPRESSION,
    UNARY_EXPRESSION,
    VARIABLE_EXPRESSION,
    ASSIGNMENT_EXPRESSION,
    ERROR_EXPRESSION,
    CALL_EXPRESSION,
    CONVERSION_EXPRESSION,
    SUFFIX_EXPRESSION,
    PREFIX_EXPRESSION,
    COMPOUND_ASSIGNMENT_EXPRESSION,
    BINARY_EXPRESSION,

    BLOCK_STATEMENT,
    EXPRESSION_STATEMENT,
    VARIABLE_DECLARATION_STATEMENT,
    IF_STATEMENT,
    ELSE_CLAUSE,
    WHILE_STATEMENT,
    FOR_STATEMENT,
    FOR_CONDITION_CLAUSE,
    JUMP_TO_STATEMENT,
    LABEL_DECLARATION_STATEMENT,
    CONDITIONAL_JUMP_TO_STATEMENT,
}
