package codeanalysis.binding.expression.binary;

public enum BoundBinaryOperatorKind {
    ADDITION,
    SUBTRACTION,
    MULTIPLICATION,
    LOGICAL_AND, LOGICAL_OR, LOGICAL_EQUALITY, LOGICAL_INEQUALITY, LESS_THAN, LESS_EQUAL_THAN, GREATER_THAN, GREATER_EQUAL_THAN, BITWISE_OR, BITWISE_AND, BITWISE_XOR, CONCATENATION, DIVISION
}
