package codeanalysis.syntax;

public enum SyntaxKind {
    //UNITS
    COMPILATION_UNIT,

    //TOKENS
    BAD_TOKEN,
    WHITESPACE_TOKEN,
    END_OF_FILE_TOKEN,
    PLUS_TOKEN,
    NUMBER_TOKEN,
    MINUS_TOKEN,
    SLASH_TOKEN,
    STAR_TOKEN,
    OPEN_PARENTHESIS_TOKEN,
    CLOSE_PARENTHESIS_TOKEN,
    EQUAL_TOKEN,
    IDENTIFIER_TOKEN,
    EQUAL_EQUAL_TOKEN,
    EXCLAMATION_EQUAL_TOKEN,
    EXCLAMATION_TOKEN,
    AMPERSAND_AMPERSAND_TOKEN,
    PIPE_PIPE_TOKEN,
    GREATER_TOKEN,
    GREATER_EQUAL_TOKEN,
    LESS_TOKEN,
    LESS_EQUAL_TOKEN,
    OPEN_BRACE_TOKEN,
    CLOSE_BRACE_TOKEN,
    TILDE_TOKEN,
    AMPERSAND_TOKEN,
    PIPE_TOKEN,
    HAT_TOKEN,
    SEMICOLON_TOKEN,
    STRING_TOKEN,
    COMMA_TOKEN,
    COLON_TOKEN,
    PERCENTAGE_TOKEN,
    PLUS_PLUS_TOKEN,
    MINUS_MINUS_TOKEN,
    PLUS_EQUALS_TOKEN,
    MINUS_EQUALS_TOKEN,
    SLASH_EQUALS_TOKEN,
    STAR_EQUALS_TOKEN,
    AMPERSAND_EQUALS_TOKEN,
    PIPE_EQUALS_TOKEN,
    HAT_EQUALS_TOKEN,

    //EXPRESSIONS
    LITERAL_EXPRESSION,
    BINARY_EXPRESSION,
    PARENTHESIZED_EXPRESSION,
    UNARY_EXPRESSION,
    NAME_EXPRESSION,
    ASSIGNMENT_EXPRESSION,
    CALL_EXPRESSION,
    PREFIX_EXPRESSION,
    SUFFIX_EXPRESSION,

    // MEMBERS
    GLOBAL_MEMBER,
    FUNCTION_MEMBER,

    //KEYWORDS
    TRUE_KEYWORD,
    FALSE_KEYWORD,
    LET_KEYWORD,
    VAR_KEYWORD,
    IF_KEYWORD,
    ELSE_KEYWORD,
    WHILE_KEYWORD,
    FOR_KEYWORD,
    FUNCTION_KEYWORD,
    CONTINUE_KEYWORD,
    BREAK_KEYWORD,

    //CLAUSES
    ElSE_CLAUSE,
    TYPE_CLAUSE,
    PARAMETER_CLAUSE,
    FOR_CONDITION_CLAUSE,

    //STATEMENTS
    EXPRESSION_STATEMENT,
    BLOCK_STATEMENT,
    VARIABLE_DECLARATION_STATEMENT,
    IF_STATEMENT,
    WHILE_STATEMENT,
    FOR_STATEMENT,
    BREAK_STATEMENT,
    CONTINUE_STATEMENT, RETURN_KEYWORD, RETURN_STATEMENT,


}
